# CACiC UnB
owner: pazkero
repo: status.cacic.bsb.br

sites:
  - name: '[VM] Agnus Dei'
    check: "tcp-ping"
    url: 75.119.128.234
    port: 443
  - name: Alumni
    url: https://alumni2.cacic.bsb.br
  - name: Website
    url: https://cacic.bsb.br
  - name: SIGAA
    url: https://sig.unb.br/sigaa/
  - name: SEI
    url: https://sei.unb.br/
  - name: Moodle
    url: https://aprender3.unb.br/login/index.php
  - name: Teams
    url: https://teams.microsoft.com/
  - name: Ouvidoria
    url: https://ouvidoria.unb.br/
  - name: Restaurante
    url: https://ru.unb.br/index.php/cardapio
  - name: Departamento
    url: http://cca.unb.br/
  - name: '[Yandex] inbound mail'
    check: "tcp-ping"
    url: mx.yandex.net
    port: 25
    icon: https://favicons.githubusercontent.com/mail.yandex.com
  - name: '[Yandex] outbound mail'
    check: "tcp-ping"
    url: smtp.yandex.com
    port: 587
    icon: https://favicons.githubusercontent.com/mail.yandex.com
  - name: Legal Aid
    url: https://adac.bsb.br
  - name: TI Aid
    url: https://moubootaurlegends.org

status-website:
  cname: status.cacic.bsb.br
  name: CACiC Status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  introTitle: "**Centro Acadêmico** de Ciências Contábeis da Universidade de Brasília"
  introMessage: Upptime — Monitora os serviços do Centro Acadêmico de Contabilidade da UnB.
  navbar:
    - title: CACiC
      href: https://cacic.bsb.br/
    - title: CCA
      href: http://cca.unb.br/index.php/graduacao
    - title: RU
      href: https://ru.unb.br/index.php/cardapio

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
